FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/backend/package.json ./apps/backend/
RUN npm install

COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend
EXPOSE 3333

CMD ["npm", "run", "dev"]
