FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/frontend/package.json ./apps/frontend/
RUN npm install

COPY apps/frontend ./apps/frontend

WORKDIR /app/apps/frontend
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
